/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Andrew Unsworth
 */
public class LoginDialog extends javax.swing.JDialog {

    /**
     * Creates new form LoginDialog
     */
    
    public LoginDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        ubMastheadPanel = new javax.swing.JPanel();
        unsBankTitle = new javax.swing.JLabel();
        unsBankStrapline = new javax.swing.JLabel();
        ubLoginPanel = new javax.swing.JPanel();
        dbTextfieldLabel = new javax.swing.JLabel();
        dbNameTextfield = new javax.swing.JTextField();
        infoLabel = new javax.swing.JLabel();
        unTextfield = new javax.swing.JTextField();
        unTextfieldLabel = new javax.swing.JLabel();
        pwTextfieldLabel = new javax.swing.JLabel();
        connectButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        pwTextfield = new javax.swing.JPasswordField();

        backgroundPanel.setBackground(new java.awt.Color(153, 153, 255));

        ubMastheadPanel.setBackground(new java.awt.Color(153, 153, 255));

        unsBankTitle.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        unsBankTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unsBankTitle.setText("UNSBank");

        unsBankStrapline.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        unsBankStrapline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unsBankStrapline.setText("Trust us, we're not like the other banks. Honest.");

        javax.swing.GroupLayout ubMastheadPanelLayout = new javax.swing.GroupLayout(ubMastheadPanel);
        ubMastheadPanel.setLayout(ubMastheadPanelLayout);
        ubMastheadPanelLayout.setHorizontalGroup(
            ubMastheadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubMastheadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ubMastheadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unsBankTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unsBankStrapline, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ubMastheadPanelLayout.setVerticalGroup(
            ubMastheadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubMastheadPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(unsBankTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unsBankStrapline, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ubLoginPanel.setBackground(new java.awt.Color(153, 153, 255));
        ubLoginPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        ubLoginPanel.setFocusCycleRoot(true);

        dbTextfieldLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        dbTextfieldLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dbTextfieldLabel.setText("Database:");

        dbNameTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dbNameTextfield.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dbNameTextfield.setText("localhost:3306/UnsBank");
        dbNameTextfield.setToolTipText("Enter the port and name fo the UNSBank database to which you want to connect.");

        infoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        infoLabel.setText("Please enter the name of the UNSBank database to whcih you want to connect, as well as the user name and password.");

        unTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        unTextfield.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        unTextfield.setToolTipText("Enter your username in this text field.");
        unTextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                unTextfieldFocusGained(evt);
            }
        });

        unTextfieldLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        unTextfieldLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unTextfieldLabel.setText("User Name:");

        pwTextfieldLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pwTextfieldLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pwTextfieldLabel.setText("Password:");

        connectButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        connectButton.setText("Connect to UNSBank");
        connectButton.setToolTipText("Click this button to connect to the UnsBank database.");
        connectButton.setMaximumSize(new java.awt.Dimension(134, 27));
        connectButton.setMinimumSize(new java.awt.Dimension(134, 27));
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cancelButton.setText("Cancel Login");
        cancelButton.setToolTipText("Click Here to cancel the login and return to the main window");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        pwTextfield.setToolTipText("Enter your password into this text field.");
        pwTextfield.setMinimumSize(new java.awt.Dimension(5, 18));
        pwTextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwTextfieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout ubLoginPanelLayout = new javax.swing.GroupLayout(ubLoginPanel);
        ubLoginPanel.setLayout(ubLoginPanelLayout);
        ubLoginPanelLayout.setHorizontalGroup(
            ubLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubLoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ubLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ubLoginPanelLayout.createSequentialGroup()
                        .addGroup(ubLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ubLoginPanelLayout.createSequentialGroup()
                                .addComponent(dbTextfieldLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dbNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ubLoginPanelLayout.createSequentialGroup()
                                .addGroup(ubLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(unTextfieldLabel)
                                    .addComponent(pwTextfieldLabel))
                                .addGap(3, 3, 3)
                                .addGroup(ubLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(unTextfield)
                                    .addComponent(pwTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)))
                            .addComponent(cancelButton))
                        .addGap(56, 56, 56)
                        .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ubLoginPanelLayout.setVerticalGroup(
            ubLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ubLoginPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ubLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbTextfieldLabel)
                    .addComponent(dbNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ubLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unTextfieldLabel)
                    .addComponent(unTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ubLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwTextfieldLabel)
                    .addComponent(pwTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ubMastheadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ubLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(ubMastheadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ubLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
         System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        // assign values of text fields to the relevant variables
        dbName = dbNameTextfield.getText();
        System.out.println("dbName: " + dbName);
        userName = unTextfield.getText();
        System.out.println("userName: " + userName);
        passWord = pwTextfield.getText();
        System.out.println("passWord: " + passWord);
        
        this.dispose();
    }//GEN-LAST:event_connectButtonActionPerformed

    private void pwTextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwTextfieldFocusGained
        pwTextfield.setText("");
    }//GEN-LAST:event_pwTextfieldFocusGained

    private void unTextfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unTextfieldFocusGained
        unTextfield.setText("");
    }//GEN-LAST:event_unTextfieldFocusGained

    public String[] getLoginData() {
        
        String[] loginData = new String[3];
        
        loginData[0] = dbName;
        loginData[1] = userName;
        loginData[2] = passWord;
        
        return loginData;
    }
    
    // variable declarations
    String dbName = new String();
    String userName = new String();
    String passWord = new String();    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton connectButton;
    private javax.swing.JTextField dbNameTextfield;
    private javax.swing.JLabel dbTextfieldLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPasswordField pwTextfield;
    private javax.swing.JLabel pwTextfieldLabel;
    private javax.swing.JPanel ubLoginPanel;
    private javax.swing.JPanel ubMastheadPanel;
    private javax.swing.JTextField unTextfield;
    private javax.swing.JLabel unTextfieldLabel;
    private javax.swing.JLabel unsBankStrapline;
    private javax.swing.JLabel unsBankTitle;
    // End of variables declaration//GEN-END:variables
}
